# docker-compose.yml

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: elearning_api
    volumes:
      - .:/var/www/html
      - ./storage:/var/www/html/storage
    depends_on:
      - db
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_URL=http://localhost:8080
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=elearning_db
      - DB_USERNAME=user
      - DB_PASSWORD=password
    networks:
      - elearning-network

  db:
    image: mysql:8.0  # Лучше использовать более новую версию
    container_name: elearning_db
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: elearning_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - elearning-network

  nginx:
    image: nginx:latest
    container_name: nginx_elearning
    ports:
      - "8080:80"
    volumes:
      - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - .:/var/www/html
    depends_on:
      - app
    networks:
      - elearning-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_elearning
    ports:
      - "8083:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: root_password
    depends_on:
      - db
    networks:
      - elearning-network

volumes:
  db_data:

networks:
  elearning-network:
    driver: bridge
