# render.yaml

services:
  - type: web
    name: e-chef-web
    runtime: php
    plan: free
    region: frankfurt
    buildCommand: |
      composer install --no-dev --optimize-autoloader
      php artisan config:cache
      php artisan route:cache
      php artisan view:cache
    startCommand: php artisan serve --host=0.0.0.0 --port=$PORT
   